#!/bin/bash

LOCAL_SCRIPT="/Users/simonbach/Teams_Status/ms-teams-status-local.sh"
EXTERNAL_SCRIPT="/Users/simonbach/Teams_Status/ms-teams-status-external.sh"

LOCAL_INTERVAL=30
EXTERNAL_INTERVAL=300

last_external=0

while true; do
  /bin/sh "$LOCAL_SCRIPT" >> /tmp/ha.msteams-status-local.out 2>> /tmp/ha.msteams-status-local.err

  now=$(date +%s)
  if [ $((now - last_external)) -ge "$EXTERNAL_INTERVAL" ]; then
    /bin/sh "$EXTERNAL_SCRIPT" >> /tmp/ha.msteams-status-external.out 2>> /tmp/ha.msteams-status-external.err
    last_external=$now
  fi

  sleep "$LOCAL_INTERVAL"
done
